spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db2
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dyzwj

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml